### ISSUE TITLE
Does this app run on iOS

### ISSUE THREAD

**Issue by postacik** [AmitJoki/Enigma#5]
Have you tested this app on iOS?

**Comment by AmitJoki** [comment]
90% of the features should work. There are some of the breaking features like #4 where the code has to be modified to reflect iOS's methods, but since I don't own a iphone, I can't test it.

Like I said, if you do have an iOS device and are willing to patch it up via a pull request, you're most welcome to do so.

**Comment by postacik** [comment]
Thanks, I'll try to test it.

**Comment by kaushik1710** [comment]
> Thanks, I'll try to test it.

have you tested it??
